openapi: "3.0.0"
info:
  title: Weatherbit Weather API
  description: API to retrieve current and daily forecast weather information
  version: 1.0.0
servers:
  - url: http://api.weatherbit.io/v2.0
paths:
  /current:
    get:
      summary: Get current weather information
      description: Retrieve current weather information based on city and country code
      parameters:
        - name: city
          in: query
          description: City name
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: Country code (ISO 3166-1 alpha-2)
          required: true
          schema:
            type: string
        - name: key
          in: query
          description: API key
          required: true
          schema:
            type: string
            example: "403f65f7bf9649c1b4e6d131a7370711"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        temp:
                          type: number
                          description: Current temperature in Celsius
                        weather:
                          type: object
                          properties:
                            description:
                              type: string
                              description: Description of the current weather condition
                        city_name:
                          type: string
                          description: Name of the city
                        country_code:
                          type: string
                          description: Country code of the location
        '401':
          description: Unauthorized - Invalid API key
        '404':
          description: City not found
  /forecast/daily:
    get:
      summary: Get daily forecast weather information
      description: Retrieve daily forecast weather information based on city and country code
      parameters:
        - name: city
          in: query
          description: City name
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: Country code (ISO 3166-1 alpha-2)
          required: true
          schema:
            type: string
        - name: key
          in: query
          description: API key
          required: true
          schema:
            type: string
            example: "403f65f7bf9649c1b4e6d131a7370711"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        datetime:
                          type: string
                          description: Date of the forecast
                        max_temp:
                          type: number
                          description: Maximum temperature in Celsius
                        min_temp:
                          type: number
                          description: Minimum temperature in Celsius
                        weather:
                          type: object
                          properties:
                            description:
                              type: string
                              description: Description of the weather condition
                        city_name:
                          type: string
                          description: Name of the city
                        country_code:
                          type: string
                          description: Country code of the location
        '401':
          description: Unauthorized - Invalid API key
        '404':
          description: City not found
